site_name: BIGM HƯỚNG DẪN SỬ DỤNG 
nav:
  - Trang chủ: index.md
  - Cửa hàng: 
    - Đăng nhập/Đăng ký:
      - Đăng ký: "auth/register.md"
      - Đăng nhập: "auth/login.md"
      - Đổi mật khẩu: "auth/reset-pass.md"
    - Quản lý cửa hàng:
      - Tạo cửa hàng: "shop/create-shop.md"
      - Cập nhật cửa hàng: "shop/update-shop.md"
      - Cập nhật hình thức thanh toán: "shop/update-payment.md"
    - Thuộc tính sản phẩm:
      - Tạo thuộc tính: "thuoctinh/create.md"
      - Chỉnh sửa thuộc tính: "thuoctinh/edit.md"
    - Sản phẩm:
      - Tạo sản phẩm: "product/create-pr.md"
      - Chỉnh sửa sản phẩm: "product/update-pr.md"
    - Khách hàng/Nhà cung cấp:
      - Tạo khách hàng/ Nhà cung cấp mới: "customer/create-cus.md"
      - Chỉnh sửa thông tin khách hàng/ Nhà cung cấp: "customer/update-cus.md"
    - Nhập hàng: 
      - Tạo đơn nhập: "import/create-import.md"
      - Xem chi tiết đơn nhập: "import/stt-import.md"
    - Đơn hàng:
      - Tạo đơn hàng: "order/create.md"
      - Xem chi tiết đơn hàng: "order/order.md"
      - Cập nhật trạng thái của đơn hàng: "order/stt-ord.md"
    - Thanh toán:
      - Thanh toán bằng mã QR: "payment/qr-pay.md"
      - Quản lý thanh toán: "payment/payment.md"
      - Kiểm tra thông tin thanh toán: "payment/match-ord.md"
      - Công nợ: "debt/qldebt.md"
    - Báo cáo:
      - Quản lý tồn kho: "stock/stock.md"
      - Báo cáo doanh thu: "reports/revenue.md"
      - Báo cáo Xuất - Nhập - Tồn: "reports/import-exist.md"
      - Báo cáo lãi lỗ: "reports/profit.md"
    - Chi phí:
      - Tạo chi phí: "cost/createcp.md"
      - Chỉnh sửa chi phí: "cost/editcp.md"
    - Giảm giá:
      - Tạo giảm giá: "cost/creategg.md"
      - Chỉnh sửa giảm giá: "cost/editgg.md"
    - Nhãn: 
      - Tạo nhãn: "tags/tags.md"
    - Danh mục:
      - Tạo danh mục: "category/create.md"
      - Chỉnh sửa danh mục: "category/edit.md"

      
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  language: vi
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow

plugins:
  - search:
      lang: 
        - vi
        - en

markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
  - attr_list

copyright: Copyright &copy; 2021 BigM. Một sản phẩm của Octa

extra:
  generator: false